[package]
name = "apply_tqa_manifest"
version = "0.1.0"
authors = ["mattlwhitaker-IO <whitaker@imageowl.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
